### ISSUE TITLE
Error when compiling with the CE C toolchain

### ISSUE THREAD

**Issue by Joshanson527** [PeterTillema/IndiumCE#3]
Errors received when compiling:

[compiling] src\commands.cpp
src/commands.cpp:113:20: error: use of undeclared identifier 'tDisp'
    if (command == tDisp) commandDisp(node->child);
__________________^
1 error generated.
make: *** [obj/src/commands.cpp.bc] Error 1

Still learning C so I don't really know what to do
Edit: the underscores are there to space the pointer where it should be

**Comment by PeterTillema** [comment]
Fixed with bd1fd604d0b2157004031af88dc4c5ba8ce8dacd
